In [14]:
import numpy as np
import pandas as pd
"""
protein structures from cullpdb servers 

The difference is that the first one(4.7GB) is divided to training/validation/test set, while the 
second one (2GB) is filtered to remove redundancy with CB513 dataset 
(for the purpose of testing performance on CB513 dataset)."
"""
data = np.load('cullpdb+profile_6133.npy.gz')
# (N protein x k features) 
"""
 You can reshape it to (N protein x 700 amino acids x 57 features) first. 
 700 is the max sequence length, except for the last sequence which is spread accross two rows

Twenty Amino Acids :
alanine - ala - A 
arginine - arg - R 
asparagine - asn - N 
aspartic acid - asp - D 
cysteine - cys - C 
glutamine - gln - Q 
glutamic acid - glu - E 
glycine - gly - G 
histidine - his - H 
isoleucine - ile - I 
leucine - leu - L 
lysine - lys - K 
methionine - met - M 
phenylalanine - phe - F 
proline - pro - P 
serine - ser - S 
threonine - thr - T 
tryptophan - trp - W 
tyrosine - tyr - Y 
valine - val - V 
asparagine/aspartic acid - asx - B
glutamine/glutamic acid - glx - Z
    
    Sometimes it is not possible two differentiate two closely related amino acids,
therefore we have the last 2 special cases above.

"""

'\n You can reshape it to (N protein x 700 amino acids x 57 features) first. \n 700 is the max sequence length, except for the last sequence which is spread accross two rows\n'

In [15]:
pdata = pd.DataFrame(data)
dataN = data.reshape((6133,700,57))
pdata.sample(10)
# pdata.describe()

,0,1,2,3,4,5,6,7,8,9,...,39890,39891,39892,39893,39894,39895,39896,39897,39898,39899
1604,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2892,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4307,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1854,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1782,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3087,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3563,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
123,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4508,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

,0,1,2,3,4,5,6,7,8,9,...,39890,39891,39892,39893,39894,39895,39896,39897,39898,39899
count,90.000000,90.000000,90.000000,90.0,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,...,90.0,90.0,90.0,90.0,90.0,90.0,90.0,90.0,90.0,90.0
mean,0.055556,0.011111,0.055556,0.0,0.122222,0.022222,0.011111,0.022222,0.066667,0.188889,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
std,0.230345,0.105409,0.230345,0.0,0.329377,0.148231,0.105409,0.148231,0.250841,0.393613,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
25%,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
50%,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
75%,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
max,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0